#!/bin/bash

if [[ $# -lt 2 ]];
then
    echo "Usage: ${0} <edits> <output>"
    exit 1
fi

editsFile=${1}
sortedEdits=${2}

echo "Getting chrM."
grep -w -E "chrM" ${editsFile} > ${sortedEdits}

contigs="chr1|"
for i in `seq 2 9`;
do
    contigs="${contigs}|chr${i}"
done

echo "Getting contigs 1-9."
grep -w -E "${contigs}" ${editsFile} >> ${sortedEdits}

echo "Getting everything else."
grep -w -E -v "chrM|${contigs}" ${editsFile} | grep -v -e "Un" -e "hap" -e "random" >> ${sortedEdits}

echo "Grep complete."