#!/bin/bash

aws ec2 run-instances --image-id ami-788c1048 --min-count 1 --max-count 1 --key-name austind@helium --subnet-id subnet-a865b3c3 --security-group-ids sg-4122ca2e --private-ip-address 10.0.0.4
