#! /bin/bash
# Starts a simple HTTP server from the current directory.

# Once started, you can navigate to t-rex:<port> in any browser to
# access the files on T-Rex.

if [ ${#} -gt 0 ]
then
  port=$1
else
  port=8080
fi

currentDir=`pwd -P`

echo "Starting local server ($(hostname):${port}) from ${currentDir}."
python -m SimpleHTTPServer ${port}
