INCLUDES=-I$(HOME)/river/users/marghoob/git/seqalto/third-party/native/include
CXXFLAGS = -g -Wall ${INCLUDES} -O3 -std=c++11
CC=g++

all: lift_over_fastq

lift_over_fastq: lift_over_fastq.o

lift_over_fastq.o: lift_over_fastq.cc
